/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityBox: typeof import('./src/components/ActivityBox.vue')['default']
    ActivityTable: typeof import('./src/components/ActivityTable.vue')['default']
    AIBox: typeof import('./src/components/AIBox.vue')['default']
    AlbumBox: typeof import('./src/components/AlbumBox.vue')['default']
    CartList: typeof import('./src/components/CartList.vue')['default']
    CollectionBox: typeof import('./src/components/CollectionBox.vue')['default']
    CollectionBoxBlindBox: typeof import('./src/components/CollectionBoxBlindBox.vue')['default']
    CollectionBoxSynthesis: typeof import('./src/components/CollectionBoxSynthesis.vue')['default']
    CollectionList: typeof import('./src/components/CollectionList.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FilterList: typeof import('./src/components/FilterList.vue')['default']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    HelpBox: typeof import('./src/components/HelpBox.vue')['default']
    HelpBoxDetail: typeof import('./src/components/HelpBoxDetail.vue')['default']
    HelpBoxHome: typeof import('./src/components/HelpBoxHome.vue')['default']
    HelpBoxMessage: typeof import('./src/components/HelpBoxMessage.vue')['default']
    LoginBox: typeof import('./src/components/LoginBox.vue')['default']
    MainNavbar: typeof import('./src/components/MainNavbar.vue')['default']
    MaskLayer: typeof import('./src/components/MaskLayer.vue')['default']
    OfferBox: typeof import('./src/components/OfferBox.vue')['default']
    OfferTable: typeof import('./src/components/OfferTable.vue')['default']
    OrderTable: typeof import('./src/components/OrderTable.vue')['default']
    PayBox: typeof import('./src/components/PayBox.vue')['default']
    QRCodeBox: typeof import('./src/components/QRCodeBox.vue')['default']
    QRCodeGenerator: typeof import('./src/components/QRCodeGenerator.vue')['default']
    Rank: typeof import('./src/components/Rank.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesInfo: typeof import('./src/components/SeriesInfo.vue')['default']
    SettingSidebar: typeof import('./src/components/SettingSidebar.vue')['default']
    SettingUserInfo: typeof import('./src/components/SettingUserInfo.vue')['default']
    Start: typeof import('./src/components/help/Start.vue')['default']
    TypeNavbar: typeof import('./src/components/TypeNavbar.vue')['default']
    UserContent: typeof import('./src/components/UserContent.vue')['default']
    UserFilterSection: typeof import('./src/components/UserFilterSection.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserNavbar: typeof import('./src/components/UserNavbar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
