/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CollectionList: typeof import('./src/components/CollectionList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginBox: typeof import('./src/components/LoginBox.vue')['default']
    MainNavbar: typeof import('./src/components/MainNavbar.vue')['default']
    MaskLayer: typeof import('./src/components/MaskLayer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Rank: typeof import('./src/components/Rank.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesInfo: typeof import('./src/components/SeriesInfo.vue')['default']
    TypeNavbar: typeof import('./src/components/TypeNavbar.vue')['default']
    UserBackground: typeof import('./src/components/UserBackground.vue')['default']
    UserContent: typeof import('./src/components/UserContent.vue')['default']
    UserFilterSection: typeof import('./src/components/UserFilterSection.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserNavbar: typeof import('./src/components/UserNavbar.vue')['default']
  }
}
